# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_shuffle_cpp <- function(a) {
    .Call(`_carsimr_prettyman_random_shuffle_cpp`, a)
}

#' Create a matrix of values 0, 1, and 2 in C++
#'
#' This function generates a grid of the specified dimensions and
#'  density with randomly distributed red and blue cars.
#'
#' @param rho - The density of cars in the grid
#' @param dims -  A vector of length 2 representing the dimensions of the grid.
#' @param prob_blue - The proportion, between 0 and 1
#' of blue squares out of total number of cars.
#' @return A NumericMatrix representing the grid,
#'  where blue and red cars are represented by 1 and 2,
#'  respectively, and no cars are represented by 0.
#'
#' @examples
#' initialize_grid_cpp(rho = 56, c(10, 10), 0.4)
#' initialize_grid_cpp(rho = 0.50, c(3, 3), 0.96)
#' @name initialize_grid_cpp
#' @export
initialize_grid_cpp <- function(rho, dims, prob_blue) {
    .Call(`_carsimr_prettyman_initialize_grid_cpp`, rho, dims, prob_blue)
}

move_red_cpp <- function(grid) {
    .Call(`_carsimr_prettyman_move_red_cpp`, grid)
}

move_blue_cpp <- function(grid) {
    .Call(`_carsimr_prettyman_move_blue_cpp`, grid)
}

#' Move both cars multiple trials in C++
#'
#' Moves the red and blue cars in a grid for
#' a specified number of trials in C++.
#'
#' @param grid A NumericMatrix representing the starting grid
#' with 0 for empty cells, 1 for blue cars, and 2 for red cars.
#' @param trials An integer specifying the number of trials to move the cars.
#' @return A List of NumericMatrices representing the grid configuration
#' after each trial, including the initial grid.
#' @name move_cars_cpp
#' @export
move_cars_cpp <- function(grid, trials) {
    .Call(`_carsimr_prettyman_move_cars_cpp`, grid, trials)
}

